# Creamos este pipeline que basicamente asemeja a una tuberia por donde pasaran todos los procesos por los que fluye la aplicacion
name: Deployment Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Install dependencies
          run: cd projects/17-pokeapi-cicd && npm install --no-audit --no-fund --no-optional
        - name: Verify Lint
          run: npm run lint
          working-directory: projects/17-pokeapi-cicd
        - name: Build project
          run: npm run build
          working-directory: projects/17-pokeapi-cicd
        - name: Start dev React project
          run: npm start &
          env:
            PORT: 5173
          working-directory: projects/17-pokeapi-cicd
        - name: Install Playwright Browsers
          run: npx playwright install --with-deps
          working-directory: projects/17-pokeapi-cicd
        - name: Run Playwright tests
          run: npx playwright test
          working-directory: projects/17-pokeapi-cicd
        - uses: actions/upload-artifact@v4
          if: ${{ !cancelled() }}
          with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30